### ISSUE TITLE
Google Resources Synchronisation

### ISSUE THREAD

**Issue by Vyacheslav-GrebenyukNURE** [nure-gs-apps/CIST-GoogleCalendarSynch#1]
Для работы календаря необходимо создать ресурсы календаря - комнаты и студенческие группы.
Первая задача - синхронизация перечня комнат:
http://cist.nure.ua/ias/app/tt/P_API_AUDITORIES_JSON
в тестовый домен dl.kture.kharkov.ua

Информация о ресурсах календаря - https://support.google.com/a/answer/1686462?hl=en
GC Resources API - https://developers.google.com/admin-sdk/directory/v1/reference/resources/calendars

**Comment by Vyacheslav-GrebenyukNURE** [comment]
`<script src="https://gist.github.com/Vyacheslav-GrebenyukNURE/3c2f5669549f48832c43a61d4d7d0e00.js"></script>`

**Comment by Vyacheslav-GrebenyukNURE** [comment]
Написанный код очень плохой и возможно трудно его будет ревьювить.

[Код на Google-sript](https://gist.github.com/Vyacheslav-GrebenyukNURE/3c2f5669549f48832c43a61d4d7d0e00)

**Comment by shevchenkobn** [comment]
Спасибо за код. Он не такой уж и плохой)

Для выполнения этого задания нужно, чтобы на моем аккунте в домене dl.kture.kharkov.ua сбросили пароль и дали права администратора. По поводу этой проблемы я отписал по почте.

**Comment by shevchenkobn** [comment]
Ресурсы создаются аккуратно, избегаются лишние обновления, используется троттлинг в случае приближения к лимиту использования за 100 секунд.
Также есть возможность удалять ресурсы (только те, что были созданы, те, которые не были созданы программой и все).
