### ISSUE TITLE
Mock расписание для тестирования

### ISSUE THREAD

**Issue by Vyacheslav-GrebenyukNURE** [nure-gs-apps/CIST-GoogleCalendarSynch#7]
Выкачать текущее расписание весеннего семестра 2018/19 и создать мок объект для тестирования функций синхронизации.

**Comment by shevchenkobn** [comment]
Есть система кэширования, сейчас выкачано вся информация за 27.04.2020 (события только для групп, не проверял на дубликаты с событиями для преподавателей и аудиторий). Кэширования сквозное и будет сохранять копию каждый раз при инвалидации кэша.
